id: opecha:P000427
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS18844
  title: གཞུང་ལམ་སྐོར་གྱི་ཀྲུང་ཧྭ་མི་དམངས་སྤྱི་མཐུན་རྒྱལ་ཁབ་ཀྱི་བཅའ་ཁྲིམས།
  volume:
    788ca3dc43524f23b900ad0a1565f87b:
      image_group_id: I8LS18846
      title: Volume 1 of gzhung lam skor gyi krung hwa mi dmangs spyi mthun rgyal
        khab kyi bca' khrims/
      volume_number: 1
      total_pages: 60
  author: ''
ebook_metadata:
  title: གཞུང་ལམ་སྐོར་གྱི་ཀྲུང་ཧྭ་མི་དམངས་སྤྱི་མཐུན་རྒྱལ་ཁབ་ཀྱི་བཅའ་ཁྲིམས།
  author: ''
  sku: P000427
  cover: cover.jpg
  layers:
  - pagination
